name: zendesk_flutter_plugin
description: A Zendesk Chat SDK Plugin.
version: 0.1.0
author: ChangeFinance <dev@getchange.com>
homepage: https://github.com/ChangeFinance/zendesk-flutter-plugin

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  package_info: ^0.4.0+6
  meta: ^1.1.7

dev_dependencies:
  test: ^1.4.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.getchange.zendesk_flutter_plugin
    pluginClass: ZendeskFlutterPlugin
